# Generated by Django 2.0.1 on 2018-01-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_opening', '0002_auto_20180107_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
